site_name: Fiware-iotagent-node-lib
site_url: https://fiware-iotagent-node-lib.readthedocs.org
repo_url: https://github.com/telefonicaid/iotagent-node-lib
site_description: IoT Agent Library Documentation
docs_dir: doc
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_iot.css"]
pages:
  - Home: 'index.md'
  - 'Getting Started' : 'getting-started.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'IoT Agent API' : 'api.md'
    - 'Advanced Topics' : 'advanced-topics.md'
    - 'Library Functions': 'usermanual.md'
    - 'Measurement Transformation Expression Language': 'expressionLanguage.md'
    - 'Caching Strategies': 'caching-strategy.md'
    - 'How to develop a new IoT Agent': 'howto.md'
    - 'North Port - NGSI Interactions': 'northboundinteractions.md'
    - 'Development Documentation': development.md
  - 'Installation & Administration Manual':
    - 'Installation Guide': 'installationguide.md'
    - 'Operations (logs & alarms)': 'operations.md'

