sonar.projectKey=telefonicaid_iotagent-node-lib_367c857f-a6e7-4f50-9fcf-f690eaacec48
sonar.projectName=iotagent-node-lib
sonar.host.url=https://sonarqube-colab.iotplatform.telefonica.com
sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*.js

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/old/**,\
  **/*.json

sonar.javascript.lcov.reportPaths=coverage/**/lcov.info

